### ISSUE TITLE
[AVM Module Issue]: azurerm provider requirement higher than other avm module

### ISSUE THREAD

**Issue by xzrians** [Azure/terraform-azurerm-avm-res-network-routetable#39]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.3.0

### Description

Basically i want to deploy RG,VNET and RT for my resources using AVM module. However 0.3.0 require ~>4.0 which is higher than other module. Appreciate if we can lower down the azurerm provider requirement.

```
module "rg" {
  source   = "Azure/avm-res-resources-resourcegroup/azurerm"
  version  = "0.1.0"
  for_each = local.resource_group
  name     = each.value.settings.name
  location = each.value.settings.location
}
```
```
module "virtualnetwork" {
  source  = "Azure/avm-res-network-virtualnetwork/azurerm"
  version = "0.6.0"
  for_each            = local.network
  name = each.value.settings.name
  address_space       = each.value.settings.address_space
  location            = var.location
  resource_group_name = module.rg["network"].name
  subnets = each.value.settings.subnets
  tags = var.resources_tags
}
```
```
module "routetable" {
  source  = "Azure/avm-res-network-routetable/azurerm"
  version = `"0.2.2"`
  for_each            = local.route_table
  name = each.value.settings.name
  location            = var.location
  resource_group_name = module.rg["network"].name
  routes = each.value.settings.routes
  subnet_resource_ids = module.virtualnetwork.subnets.value.id
}
```
RG and VNET module 

```
RG require 
version = "~> 3.71"
```

```
VNET require
version = ">= 3.116, < 5"
```

```
RT 0.3.0 require 
version ~> 4.0 

RT 0.2.2 require
 version = ">= 3.71.0, < 4.0"
```

Error prompting no match for provider for verion 0.3.0
![Image](https://github.com/user-attachments/assets/2edb2e42-dbe8-4297-b498-f8dc578a4da4)

**Comment by adammontlake** [comment]
Hey @xzrians, thanks for taking the time to write feedback!

Based on the above, and I have validated, if you use the following combination of versions it will be fine:
RG: 0.1.0
VNet: 0.6.0
RT: 0.2.2

They should all be fine with version 3.116.0 (the most recent version 3). 

However, that being said, you could also use each module with a different AzureRM version!
Here is an example:

`# Define the first azapi provider instance with version 1.x
provider "azapi" {
  version = "~> 1.0"
  alias   = "v1"
  features {}
}
 
# Define the second azapi provider instance with version 2.x
provider "azapi" {
  version = "~> 2.0"
  alias   = "v2"
  features {}
}
 `

`# Call the first module with azapi provider version 1.x
module "module_one" {
  source    = "./module_one"
  providers = {
    azapi = azapi.v1
  }
}
 
# Call the second module with azapi provider version 2.x
module "module_two" {
  source    = "./module_two"
  providers = {
    azapi = azapi.v2
  }
}`

Two things to note:
1. The reason routetable does not have compatibility between v3.x.x and v4.x.x is because the name of the parameter "disable_bgp_route_propagation" was changed to "bgp_route_propagation_enabled". I have considered doing some trickery to try and determine the AzureRM version and use the correct parameter, but this seems like overengineering an issue, this is the way the provider was designed.
2. You are not the first to raise this issue! I will start a conversation internally in AVM to see if there might be a way to provide "compatible" module versions in some way

Hope this helps, feel free to open more issues if you find any!
